### ISSUE TITLE
签到

### ISSUE THREAD

**Issue by kang000feng** [Orz-3/QuantumultX#18]
@Orz-3 您好大神，请问您项目中的 无忧行签到报错了，是脚本的问题吗？ 谢谢🙏
脚本 https://ooxx.be/js/jegotrip.js 运行报错 ：[JegoTrip] LOG: 状态获取失败⚠️ ，我又尝试重新获取无忧行 cookie, 
如下： 获取无忧行 Cookie2: SyntaxError: JSON Parse error: Property name must be a string literal. Line number 246, column: 26  看了一下246行没有语法错误呀。请问该怎么排查？谢谢

**Comment by Orz-3** [comment]
此脚本没有更新，可以试着tg内寻找作者询问...我只是收集而已

**Comment by kang000feng** [comment]
> 此脚本没有更新，可以试着tg内寻找作者询问...我只是收集而已

谢谢🙏，请问在哪个tg号/group 可以找到作者￼？￼
