### ISSUE TITLE
tb_price失效了，大佬可以换成这个

### ISSUE THREAD

**Issue by StimeKe** [Orz-3/QuantumultX#26]
脚本：https://service.2ti.st/QuanX/Script/jd_tb_price/main.js
支持京东和淘宝，昨天我自己写的

**Comment by Orz-3** [comment]
收到！大佬威武

**Comment by XieL1989** [comment]
> 脚本：https://service.2ti.st/QuanX/Script/jd_tb_price/main.js
> 
> 支持京东和淘宝，昨天我自己写的

失效了大佬，有更新嘛

**Comment by StimeKe** [comment]
> > 脚本：https://service.2ti.st/QuanX/Script/jd_tb_price/main.js
> > 支持京东和淘宝，昨天我自己写的
> 
> 失效了大佬，有更新嘛

已经修复了，更新下脚本吧

**Comment by imzhonghao** [comment]
> > > 脚本：https://service.2ti.st/QuanX/Script/jd_tb_price/main.js
> > > 支持京东和淘宝，昨天我自己写的
> > 
> > 
> > 失效了大佬，有更新嘛
> 
> 已经修复了，更新下脚本吧

更新了之后比价是错的....虽然出来了，但是比价的价格不是我看的商品。。很迷

**Comment by StimeKe** [comment]
> 

再次修复了！！！（真的修复了）

**Comment by StimeKe** [comment]
> > > > 脚本：https://service.2ti.st/QuanX/Script/jd_tb_price/main.js
> > > > 支持京东和淘宝，昨天我自己写的
> > > 
> > > 
> > > 失效了大佬，有更新嘛
> > 
> > 
> > 已经修复了，更新下脚本吧
> 
> 更新了之后比价是错的....虽然出来了，但是比价的价格不是我看的商品。。很迷

再次修复了！！！（真的修复了）

**Comment by XieL1989** [comment]
感谢，终于正常了




Dr.Xie
***@***.***




------------------ 原始邮件 ------------------
发件人: Small_Ke ***@***.***&gt;
发送时间: 2021年11月28日 23:06
收件人: Orz-3/QuantumultX ***@***.***&gt;
抄送: 狮子座 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Orz-3/QuantumultX] tb_price失效了，大佬可以换成这个 (#26)





     
脚本：https://service.2ti.st/QuanX/Script/jd_tb_price/main.js
 支持京东和淘宝，昨天我自己写的
  
失效了大佬，有更新嘛
  
已经修复了，更新下脚本吧
  
更新了之后比价是错的....虽然出来了，但是比价的价格不是我看的商品。。很迷
  
再次修复了！！！（真的修复了）

**Comment by imzhonghao** [comment]
> > > > > 脚本：https://service.2ti.st/QuanX/Script/jd_tb_price/main.js
> > > > > 支持京东和淘宝，昨天我自己写的
> > > > 
> > > > 
> > > > 失效了大佬，有更新嘛
> > > 
> > > 
> > > 已经修复了，更新下脚本吧
> > 
> > 
> > 更新了之后比价是错的....虽然出来了，但是比价的价格不是我看的商品。。很迷
> 
> 再次修复了！！！（真的修复了）

测试正常，感谢大佬。

**Comment by spirytuslove** [comment]
> > > > > 脚本：https://service.2ti.st/QuanX/Script/jd_tb_price/main.js
> > > > > 支持京东和淘宝，昨天我自己写的
> > > > 
> > > > 
> > > > 失效了大佬，有更新嘛
> > > 
> > > 
> > > 已经修复了，更新下脚本吧
> > 
> > 
> > 更新了之后比价是错的....虽然出来了，但是比价的价格不是我看的商品。。很迷
> 
> 再次修复了！！！（真的修复了）

大佬好像还是不行啊  价格不对

**Comment by oniyou** [comment]
再次失效了，大佬，更新一下吧

**Comment by GitHubaibuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YangZhaocool** [comment]
京东价格不对 淘宝开了之后打不开详情页
