### ISSUE TITLE
测速模块麻烦排除关键字“试用“的“试”字

### ISSUE THREAD

**Issue by Nautilus-Erkkinen** [Orz-3/QuantumultX#39]
机场订阅中有带限速的试用服务器，因为负载低所以往往延迟也低，在测速中经常被自动选用。希望考虑增加关键字排除，排除“试”字，或者trial什么的。
`url-latency-benchmark=香港节点, server-tag-regex=(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|美|试)).)*$, check-interval=600, tolerance=0, img-url=https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png`

**Comment by Orz-3** [comment]
自行排除，你应该意识到这是你机场的问题
