### ISSUE TITLE
上游地址变更导致zhihu资源更新时404

### ISSUE THREAD

**Issue by THU-Pieris** [Orz-3/QuantumultX#40]
`https://raw.githubusercontent.com/Orz-3/QuantumultX/master/JS.conf` 内引用的「知乎去广告」，规则从`/script/zhihu/zhihu_plus.js`变成了`/script/zhihu/zhihu_plus.qxrewrite`，请更改相应位置。

**Comment by GitHubaibuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Orz-3** [comment]
此重写订阅是从神机规则引用的，等神机更新即可
