### ISSUE TITLE
如何指定各个地区节点选择

### ISSUE THREAD

**Issue by FivespeedDoc** [Orz-3/QuantumultX#43]
我的机场拥有多个不同国家的节点，我怎么样才可以在自定义策略的相应菜单栏选择具体节点呢？例如：香港节点 选择我想要使用的节点 目前这些栏无法点选展开菜单里面的节点。并且会自动切换，请问有什么办法改变吗。

**Comment by 5hrike** [comment]
把策略中的 url-latency-benchmark 改为static
