### ISSUE TITLE
比价脚本已经不能使用了

### ISSUE THREAD

**Issue by nekore** [Orz-3/QuantumultX#49]
淘宝重新卸载，一直开着脚本，都不行了

**Comment by GitHubaibuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nekore** [comment]
噢，我重新激活安装了BoX.JS以后，功能好了。京东还是不行。
