### ISSUE TITLE
getcookie 里 wangdelu2020已经失效.他删除了项目

### ISSUE THREAD

**Issue by Xylotox** [Orz-3/QuantumultX#5]
#wangdelu2020
#趣走
https:\/\/mobile01\.91quzou\.com\/rebate\/qz\/task\/homeTaskView\.do url script-request-header https://raw.githubusercontent.com/wangdelu2020/hongliyu/master/quwalk2.2.js
#陌陌
https:\/\/mk\.immomo\.com\/activity\/fastsign\/index\/signIn? url script-request-body https://raw.githubusercontent.com/wangdelu2020/hongliyu/master/momosign.js
#惠头条
https:\/\/api\.cashtoutiao\.com url script-request-body https://raw.githubusercontent.com/wangdelu2020/hongliyu/master/htt_cookie.js
#趣看天下
https:\/\/(appv8\.qukantianxia\.com|appv7\.qukantx\.com) url script-request-header https://raw.githubusercontent.com/wangdelu2020/hongliyu/master/qktx_cookie.js
#微信打卡
https:\/\/(www\.baimaa\.com|www\.2xtj7\.cn|www\.hnmiaosu\.cc)\/app\/index\.php? url script-request-header https://raw.githubusercontent.com/wangdelu2020/hongliyu/master/wxdaka.js
#联通流量话费提醒
https:\/\/m.client\.10010\.com\/mobileService\/home\/queryUserInfoSeven\.htm? url script-request-header https://raw.githubusercontent.com/wangdelu2020/hongliyu/master/liantongnotice.js
#新浪超话签到
https:\/\/m\.weibo\.cn\/api\/config url script-request-header https://raw.githubusercontent.com/wangdelu2020/hongliyu/master/newsinachaohua.js

**Comment by Orz-3** [comment]
感谢提醒，已处理
